FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o /app/worker_bin ./worker/geofence_worker.go

RUN chmod +x /app/worker_bin

CMD ["/app/worker_bin"]