FROM golang:1.23-alpine

WORKDIR /app/publisher

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o /app/publisher_bin ./publisher/mock_publisher.go

RUN ls -lah /app && chmod +x /app/publisher_bin

CMD ["/app/publisher_bin"]